// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaWDoD93OrEfAF9qbAYk2Ugft7FGdgJWA',
    appId: '1:280884779698:web:25c9d57edc366a2f88c7ab',
    messagingSenderId: '280884779698',
    projectId: 'damkargarutapp',
    authDomain: 'damkargarutapp.firebaseapp.com',
    storageBucket: 'damkargarutapp.firebasestorage.app',
    measurementId: 'G-DVFV13LE60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvAjtyHnfCP7-EC5cawS0KxcUBSodGGk',
    appId: '1:280884779698:android:19b6b2942f64119088c7ab',
    messagingSenderId: '280884779698',
    projectId: 'damkargarutapp',
    storageBucket: 'damkargarutapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aJeJaRctQ3ETnJ52mjpr9fV34XwVEGs',
    appId: '1:280884779698:ios:b0e38d09c70f40b588c7ab',
    messagingSenderId: '280884779698',
    projectId: 'damkargarutapp',
    storageBucket: 'damkargarutapp.firebasestorage.app',
    iosBundleId: 'com.example.kerjapraktek',
  );
}
